version: "3.9"

services:
  web:
    build: .
    container_name: rag_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - qdrant
    restart: always

  db:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  postgres_data:
  qdrant_data:
